# Generated by Django 3.2.25 on 2025-05-17 07:57

from django.db import migrations
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='visible',
        ),
        migrations.AddField(
            model_name='exam',
            name='desc',
            field=utils.models.RichTextField(default=''),
        ),
    ]
