# Generated by Django 3.2.25 on 2025-05-18 10:14

from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20250517_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examdetail',
            name='category',
        ),
        migrations.RemoveField(
            model_name='examdetail',
            name='exam',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_detail_A',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_detail_A', to='exam.examdetail'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_detail_B',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_detail_B', to='exam.examdetail'),
        ),
        migrations.AddField(
            model_name='examdetail',
            name='desc',
            field=utils.models.RichTextField(default=''),
        ),
    ]
