# Generated by Django 3.2.25 on 2025-05-18 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20250518_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_detail_A',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_detail_B',
        ),
        migrations.CreateModel(
            name='ExamToExamDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('exam_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examdetail')),
            ],
            options={
                'db_table': 'exam_to_exam_detail',
                'unique_together': {('exam', 'exam_detail')},
            },
        ),
    ]
