# Generated by Django 3.2.25 on 2025-05-18 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20250518_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetail',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examdetail',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examdetail',
            name='name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
