# Generated by Django 3.2.25 on 2025-08-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20250518_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='ex_number',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='ex_room',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sub_college',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
