# Generated by Django 3.2.25 on 2025-08-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20250815_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
