# Generated by Django 3.2.25 on 2025-08-17 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_exam_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='status',
        ),
    ]
