# Generated by Django 3.2.25 on 2025-09-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_remove_exam_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
