# Generated by Django 3.2.25 on 2025-05-18 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20250518_1814'),
        ('submission', '0014_submission_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='exam_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.examdetail'),
        ),
    ]
